### ISSUE TITLE
Wrong UpdateStylesNonRecursively binding

### ISSUE THREAD

**Issue by redent** [Pixate/Xamarin-PixateFreestyle#3]
Calls to this method causes a crash with the following exception:

```
NSInvalidArgumentException Reason: +[PXEngine updateStylesnonRecursively:]: unrecognized selector sent to class 0x43dad8
```

The binding should be `updateStylesNonRecursively`, but it is `updateStylesnonRecursively` at this line:
https://github.com/Pixate/Xamarin-Pixate/blob/master/Source/Pixate/ApiDefinition.cs#L81

**Comment by pcolton** [comment]
Thanks, we've corrected the typo and we'll push a new binary version shortly.
