### ISSUE TITLE
PixateConfiguration.UpdateStylesType doesn't exist

### ISSUE THREAD

**Issue by redent** [Pixate/Xamarin-PixateFreestyle#4]
There's a binding property named UpdateStylesType in PixateConfiguration class, but this property doesn't exist in the Obj-C library, so setting it or getting it crashes the App.

**Comment by pcolton** [comment]
In the current code base, these are the only two methods that are mapped:

```
    interface PixateFreestyleConfiguration {
        [Export ("parseErrorDestination")]
        PXParseErrorDestination ParseErrorDestination { get; set; }

        [Export ("cacheStylesType")]
        PXCacheStylesType CacheStylesType { get; set; }
    }
```
